services:
  analytics_api:
    container_name: analytics-api-container
    build:
      context: ..
      dockerfile: src/Analytics.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod
      - DatabaseOptions__ConnectionString=${ConnectionString_Key}      
      
    restart: unless-stopped    
    networks:
      - public-network
    labels:      
      - "traefik.enable=true"      
      - "traefik.http.routers.analytics-api.rule=Host(`api.cloud-platform.pro`) && PathPrefix(`/data-analyst`)"      
      - "traefik.http.routers.analytics-api.entrypoints=websecure"      
      - "traefik.http.routers.analytics-api.tls.certresolver=letsencrypt"     
      - "traefik.http.services.analytics-api.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.analytics-stripprefix.stripprefix.prefixes=/data-analyst"
      - "traefik.http.routers.analytics-api.middlewares=data-analyst-stripprefix"

networks:
  public-network:
    external: true